/**
 * Large curated food database for search + autofill.
 *
 * Covers Tamil Nadu (tiffin, meals, gravies, non-veg, snacks, sweets), broader
 * Indian (North/street food/sweets), Bangladeshi, and hotel/restaurant dishes.
 * Macros are per the stated typical serving — good estimates, not lab values.
 * Users can still add their own via "Save as my custom food".
 */
import type { FoodItem } from './seed'

export const INDIAN_FOOD_DB: FoodItem[] = [
  // ============ TAMIL NADU — Breakfast / Tiffin ============
  { name: 'Idli', serving: '2 pcs', calories: 116, protein: 4, carbs: 24, fat: 1 },
  { name: 'Mini Idli (Sambar)', serving: '8 pcs', calories: 260, protein: 8, carbs: 44, fat: 5 },
  { name: 'Rava Idli', serving: '2 pcs', calories: 190, protein: 5, carbs: 32, fat: 5 },
  { name: 'Kanchipuram Idli', serving: '1 pc', calories: 170, protein: 5, carbs: 28, fat: 4 },
  { name: 'Plain Dosa', serving: '1 pc', calories: 168, protein: 4, carbs: 29, fat: 4 },
  { name: 'Masala Dosa', serving: '1 pc', calories: 290, protein: 6, carbs: 45, fat: 9 },
  { name: 'Ghee Roast Dosa', serving: '1 pc', calories: 330, protein: 6, carbs: 44, fat: 14 },
  { name: 'Onion Rava Dosa', serving: '1 pc', calories: 270, protein: 5, carbs: 36, fat: 12 },
  { name: 'Set Dosa', serving: '2 pcs', calories: 240, protein: 6, carbs: 40, fat: 6 },
  { name: 'Egg Dosa', serving: '1 pc', calories: 230, protein: 9, carbs: 29, fat: 9 },
  { name: 'Paneer Dosa', serving: '1 pc', calories: 320, protein: 12, carbs: 40, fat: 13 },
  { name: 'Kal Dosa', serving: '1 pc', calories: 130, protein: 3, carbs: 24, fat: 2 },
  { name: 'Adai', serving: '1 pc', calories: 210, protein: 9, carbs: 28, fat: 7 },
  { name: 'Pesarattu', serving: '1 pc', calories: 180, protein: 9, carbs: 26, fat: 4 },
  { name: 'Uttapam', serving: '1 pc', calories: 200, protein: 5, carbs: 32, fat: 6 },
  { name: 'Onion Uttapam', serving: '1 pc', calories: 220, protein: 5, carbs: 34, fat: 7 },
  { name: 'Medu Vada', serving: '2 pcs', calories: 280, protein: 8, carbs: 30, fat: 14 },
  { name: 'Pongal (Ven)', serving: '1 cup', calories: 300, protein: 8, carbs: 40, fat: 12 },
  { name: 'Sakkarai Pongal', serving: '1 cup', calories: 380, protein: 6, carbs: 62, fat: 12 },
  { name: 'Rava Upma', serving: '1 cup', calories: 250, protein: 6, carbs: 38, fat: 8 },
  { name: 'Aval Upma (Poha)', serving: '1 cup', calories: 230, protein: 5, carbs: 38, fat: 7 },
  { name: 'Semiya Upma', serving: '1 cup', calories: 240, protein: 6, carbs: 40, fat: 6 },
  { name: 'Idiyappam', serving: '3 pcs', calories: 200, protein: 4, carbs: 44, fat: 1 },
  { name: 'Appam', serving: '1 pc', calories: 120, protein: 2, carbs: 23, fat: 2 },
  { name: 'Egg Appam', serving: '1 pc', calories: 190, protein: 8, carbs: 24, fat: 7 },
  { name: 'Aappam with Coconut Milk', serving: '2 pcs', calories: 300, protein: 5, carbs: 46, fat: 11 },
  { name: 'Kuzhi Paniyaram', serving: '5 pcs', calories: 220, protein: 6, carbs: 32, fat: 8 },
  { name: 'Puttu', serving: '1 cup', calories: 230, protein: 5, carbs: 44, fat: 4 },
  { name: 'Kothu Parotta', serving: '1 plate', calories: 480, protein: 16, carbs: 56, fat: 22 },
  { name: 'Egg Kothu Parotta', serving: '1 plate', calories: 540, protein: 20, carbs: 56, fat: 26 },
  { name: 'Parotta', serving: '1 pc', calories: 260, protein: 6, carbs: 36, fat: 10 },
  { name: 'Veg Kurma (for parotta)', serving: '1 cup', calories: 180, protein: 5, carbs: 18, fat: 10 },
  { name: 'Sevai (Lemon)', serving: '1 cup', calories: 260, protein: 5, carbs: 46, fat: 7 },
  { name: 'Wheat Dosa (Godhumai)', serving: '1 pc', calories: 150, protein: 4, carbs: 26, fat: 3 },
  { name: 'Ragi Dosa', serving: '1 pc', calories: 160, protein: 5, carbs: 28, fat: 3 },
  { name: 'Kambu Koozh', serving: '1 cup', calories: 200, protein: 6, carbs: 38, fat: 3 },
  { name: 'Ragi Koozh', serving: '1 cup', calories: 180, protein: 5, carbs: 36, fat: 2 },

  // ============ TAMIL NADU — Rice & Meals ============
  { name: 'Curd Rice', serving: '1 cup', calories: 230, protein: 7, carbs: 38, fat: 5 },
  { name: 'Lemon Rice', serving: '1 cup', calories: 290, protein: 5, carbs: 48, fat: 9 },
  { name: 'Tamarind Rice (Puliyodharai)', serving: '1 cup', calories: 320, protein: 5, carbs: 52, fat: 10 },
  { name: 'Coconut Rice', serving: '1 cup', calories: 330, protein: 6, carbs: 48, fat: 13 },
  { name: 'Tomato Rice', serving: '1 cup', calories: 300, protein: 6, carbs: 50, fat: 9 },
  { name: 'Vegetable Biryani', serving: '1 plate', calories: 380, protein: 9, carbs: 58, fat: 12 },
  { name: 'Seeraga Samba Veg Biryani', serving: '1 plate', calories: 360, protein: 9, carbs: 56, fat: 11 },
  { name: 'Chicken Biryani', serving: '1 plate', calories: 490, protein: 22, carbs: 62, fat: 16 },
  { name: 'Ambur Chicken Biryani', serving: '1 plate', calories: 520, protein: 24, carbs: 64, fat: 18 },
  { name: 'Dindigul Mutton Biryani', serving: '1 plate', calories: 600, protein: 26, carbs: 64, fat: 26 },
  { name: 'Egg Biryani', serving: '1 plate', calories: 440, protein: 16, carbs: 60, fat: 14 },
  { name: 'Sambar Rice (Bisi Bele)', serving: '1 cup', calories: 320, protein: 10, carbs: 50, fat: 9 },
  { name: 'Curd Rice (Thayir Sadam)', serving: '1 cup', calories: 220, protein: 7, carbs: 36, fat: 5 },
  { name: 'South Indian Veg Meals (full)', serving: '1 plate', calories: 720, protein: 18, carbs: 120, fat: 18 },
  { name: 'Plain Rice (cooked)', serving: '1 cup', calories: 205, protein: 4, carbs: 45, fat: 0 },

  // ============ TAMIL NADU — Gravies / Kuzhambu / Sambar / Rasam ============
  { name: 'Sambar', serving: '1 cup', calories: 140, protein: 7, carbs: 20, fat: 4 },
  { name: 'Drumstick Sambar', serving: '1 cup', calories: 150, protein: 7, carbs: 21, fat: 4 },
  { name: 'Rasam', serving: '1 cup', calories: 65, protein: 3, carbs: 11, fat: 1 },
  { name: 'Pepper Rasam', serving: '1 cup', calories: 60, protein: 3, carbs: 10, fat: 1 },
  { name: 'Vathal Kuzhambu', serving: '1 cup', calories: 170, protein: 4, carbs: 18, fat: 9 },
  { name: 'Puli Kuzhambu', serving: '1 cup', calories: 160, protein: 4, carbs: 18, fat: 8 },
  { name: 'Mor Kuzhambu', serving: '1 cup', calories: 150, protein: 5, carbs: 12, fat: 9 },
  { name: 'Kara Kuzhambu', serving: '1 cup', calories: 180, protein: 5, carbs: 18, fat: 10 },
  { name: 'Ennai Kathirikai', serving: '1 cup', calories: 220, protein: 4, carbs: 18, fat: 15 },
  { name: 'Poricha Kuzhambu', serving: '1 cup', calories: 150, protein: 6, carbs: 18, fat: 6 },

  // ============ TAMIL NADU — Poriyal / Kootu / Veg sides ============
  { name: 'Cabbage Poriyal', serving: '1 cup', calories: 110, protein: 4, carbs: 12, fat: 6 },
  { name: 'Beans Poriyal', serving: '1 cup', calories: 120, protein: 5, carbs: 12, fat: 6 },
  { name: 'Carrot Poriyal', serving: '1 cup', calories: 120, protein: 3, carbs: 14, fat: 6 },
  { name: 'Beetroot Poriyal', serving: '1 cup', calories: 130, protein: 3, carbs: 16, fat: 6 },
  { name: 'Keerai Poriyal (Greens)', serving: '1 cup', calories: 100, protein: 5, carbs: 9, fat: 5 },
  { name: 'Kothavarangai Poriyal', serving: '1 cup', calories: 120, protein: 5, carbs: 13, fat: 6 },
  { name: 'Avial', serving: '1 cup', calories: 180, protein: 5, carbs: 16, fat: 11 },
  { name: 'Kootu (mixed veg)', serving: '1 cup', calories: 160, protein: 7, carbs: 20, fat: 6 },
  { name: 'Pudalangai Kootu', serving: '1 cup', calories: 140, protein: 6, carbs: 16, fat: 6 },
  { name: 'Vendakai (Okra) Fry', serving: '1 cup', calories: 170, protein: 4, carbs: 16, fat: 10 },
  { name: 'Aloo Masala (Potato)', serving: '1 cup', calories: 180, protein: 4, carbs: 28, fat: 6 },
  { name: 'Urulai Roast', serving: '1 cup', calories: 220, protein: 4, carbs: 30, fat: 10 },
  { name: 'Mushroom Pepper Fry', serving: '1 cup', calories: 180, protein: 6, carbs: 10, fat: 12 },

  // ============ TAMIL NADU — Non-veg ============
  { name: 'Chicken Chettinad', serving: '1 cup', calories: 320, protein: 28, carbs: 9, fat: 19 },
  { name: 'Chicken Curry (TN style)', serving: '1 cup', calories: 280, protein: 26, carbs: 8, fat: 16 },
  { name: 'Pepper Chicken', serving: '1 cup', calories: 300, protein: 30, carbs: 6, fat: 17 },
  { name: 'Chicken 65', serving: '1 plate', calories: 350, protein: 28, carbs: 16, fat: 20 },
  { name: 'Mutton Kuzhambu', serving: '1 cup', calories: 360, protein: 26, carbs: 8, fat: 25 },
  { name: 'Mutton Chukka', serving: '1 cup', calories: 340, protein: 30, carbs: 6, fat: 22 },
  { name: 'Fish Fry (Meen Varuval)', serving: '2 pcs', calories: 260, protein: 28, carbs: 6, fat: 14 },
  { name: 'Fish Curry (Meen Kuzhambu)', serving: '1 cup', calories: 220, protein: 24, carbs: 8, fat: 11 },
  { name: 'Prawn Masala', serving: '1 cup', calories: 250, protein: 26, carbs: 9, fat: 13 },
  { name: 'Nethili Fry (Anchovy)', serving: '1 plate', calories: 240, protein: 24, carbs: 8, fat: 13 },
  { name: 'Egg Curry', serving: '1 cup (2 eggs)', calories: 270, protein: 16, carbs: 9, fat: 19 },
  { name: 'Egg Poriyal / Podimas', serving: '1 cup', calories: 220, protein: 14, carbs: 6, fat: 16 },
  { name: 'Boiled Egg', serving: '1 large', calories: 78, protein: 6, carbs: 1, fat: 5 },
  { name: 'Omelette', serving: '2 eggs', calories: 190, protein: 13, carbs: 2, fat: 15 },

  // ============ TAMIL NADU — Chutneys / Podis / Accompaniments ============
  { name: 'Coconut Chutney', serving: '2 tbsp', calories: 90, protein: 2, carbs: 4, fat: 8 },
  { name: 'Tomato Chutney', serving: '2 tbsp', calories: 60, protein: 1, carbs: 7, fat: 3 },
  { name: 'Onion Chutney', serving: '2 tbsp', calories: 70, protein: 1, carbs: 8, fat: 4 },
  { name: 'Groundnut Chutney', serving: '2 tbsp', calories: 110, protein: 4, carbs: 6, fat: 8 },
  { name: 'Mint Chutney', serving: '2 tbsp', calories: 40, protein: 1, carbs: 5, fat: 2 },
  { name: 'Thuvaiyal (Coconut)', serving: '2 tbsp', calories: 100, protein: 2, carbs: 5, fat: 8 },
  { name: 'Idli Podi with Oil', serving: '1 tbsp', calories: 90, protein: 3, carbs: 6, fat: 6 },
  { name: 'Appalam (fried)', serving: '1 pc', calories: 60, protein: 2, carbs: 8, fat: 3 },
  { name: 'Curd (plain)', serving: '1 cup', calories: 98, protein: 5, carbs: 7, fat: 5 },
  { name: 'Buttermilk (Mor)', serving: '1 glass', calories: 40, protein: 2, carbs: 4, fat: 2 },

  // ============ TAMIL NADU — Snacks & Sweets ============
  { name: 'Masala Vada', serving: '2 pcs', calories: 220, protein: 8, carbs: 24, fat: 11 },
  { name: 'Bonda', serving: '2 pcs', calories: 240, protein: 4, carbs: 30, fat: 12 },
  { name: 'Bajji (Mixed)', serving: '3 pcs', calories: 250, protein: 5, carbs: 30, fat: 13 },
  { name: 'Sundal (Chickpea)', serving: '1 cup', calories: 180, protein: 9, carbs: 28, fat: 4 },
  { name: 'Murukku', serving: '2 pcs', calories: 180, protein: 3, carbs: 18, fat: 11 },
  { name: 'Mixture', serving: '50g', calories: 270, protein: 6, carbs: 26, fat: 16 },
  { name: 'Thattai', serving: '2 pcs', calories: 150, protein: 3, carbs: 16, fat: 9 },
  { name: 'Banana Chips', serving: '30g', calories: 160, protein: 1, carbs: 17, fat: 10 },
  { name: 'Mysore Pak', serving: '1 pc', calories: 230, protein: 2, carbs: 24, fat: 14 },
  { name: 'Jangiri', serving: '1 pc', calories: 180, protein: 2, carbs: 28, fat: 7 },
  { name: 'Adhirasam', serving: '1 pc', calories: 200, protein: 2, carbs: 34, fat: 7 },
  { name: 'Payasam (Semiya)', serving: '1 cup', calories: 280, protein: 6, carbs: 42, fat: 10 },
  { name: 'Paruppu Payasam', serving: '1 cup', calories: 300, protein: 7, carbs: 46, fat: 10 },
  { name: 'Kesari', serving: '1 cup', calories: 320, protein: 4, carbs: 50, fat: 12 },
  { name: 'Sweet Avul Puttu', serving: '1 cup', calories: 260, protein: 4, carbs: 44, fat: 8 },

  // ============ South Indian beverages ============
  { name: 'Filter Coffee (milk+sugar)', serving: '1 cup', calories: 90, protein: 3, carbs: 12, fat: 3 },
  { name: 'Masala Tea (Chai)', serving: '1 cup', calories: 90, protein: 2, carbs: 14, fat: 3 },
  { name: 'Sukku Malli Coffee', serving: '1 cup', calories: 35, protein: 0, carbs: 8, fat: 0 },
  { name: 'Badam Milk', serving: '1 glass', calories: 180, protein: 7, carbs: 24, fat: 6 },
  { name: 'Rose Milk', serving: '1 glass', calories: 200, protein: 6, carbs: 32, fat: 5 },
  { name: 'Nannari Sharbat', serving: '1 glass', calories: 120, protein: 0, carbs: 30, fat: 0 },
  { name: 'Tender Coconut Water', serving: '1 glass', calories: 60, protein: 1, carbs: 14, fat: 0 },

  // ============ NORTH INDIAN — Breads ============
  { name: 'Chapati / Roti', serving: '1 pc', calories: 104, protein: 3, carbs: 18, fat: 2 },
  { name: 'Phulka', serving: '1 pc', calories: 80, protein: 3, carbs: 16, fat: 1 },
  { name: 'Plain Naan', serving: '1 pc', calories: 260, protein: 9, carbs: 45, fat: 5 },
  { name: 'Butter Naan', serving: '1 pc', calories: 320, protein: 9, carbs: 46, fat: 12 },
  { name: 'Garlic Naan', serving: '1 pc', calories: 300, protein: 9, carbs: 45, fat: 10 },
  { name: 'Tandoori Roti', serving: '1 pc', calories: 130, protein: 4, carbs: 24, fat: 2 },
  { name: 'Aloo Paratha', serving: '1 pc', calories: 290, protein: 6, carbs: 42, fat: 10 },
  { name: 'Gobi Paratha', serving: '1 pc', calories: 270, protein: 6, carbs: 40, fat: 9 },
  { name: 'Paneer Paratha', serving: '1 pc', calories: 320, protein: 11, carbs: 40, fat: 13 },
  { name: 'Plain Paratha (Lachha)', serving: '1 pc', calories: 260, protein: 5, carbs: 38, fat: 10 },
  { name: 'Kulcha', serving: '1 pc', calories: 280, protein: 8, carbs: 46, fat: 7 },
  { name: 'Bhatura', serving: '1 pc', calories: 300, protein: 6, carbs: 42, fat: 12 },
  { name: 'Poori', serving: '2 pcs', calories: 280, protein: 5, carbs: 34, fat: 14 },

  // ============ NORTH INDIAN — Dals & Legumes ============
  { name: 'Dal Tadka', serving: '1 cup', calories: 200, protein: 12, carbs: 28, fat: 5 },
  { name: 'Dal Fry', serving: '1 cup', calories: 230, protein: 12, carbs: 28, fat: 8 },
  { name: 'Dal Makhani', serving: '1 cup', calories: 330, protein: 13, carbs: 30, fat: 18 },
  { name: 'Rajma', serving: '1 cup', calories: 230, protein: 13, carbs: 38, fat: 3 },
  { name: 'Chana Masala', serving: '1 cup', calories: 270, protein: 12, carbs: 40, fat: 7 },
  { name: 'Chole', serving: '1 cup', calories: 290, protein: 12, carbs: 42, fat: 8 },
  { name: 'Lobia (Black-eyed pea)', serving: '1 cup', calories: 220, protein: 13, carbs: 36, fat: 3 },
  { name: 'Moong Dal', serving: '1 cup', calories: 180, protein: 12, carbs: 26, fat: 3 },
  { name: 'Sprouts Salad', serving: '1 cup', calories: 140, protein: 10, carbs: 24, fat: 2 },

  // ============ NORTH INDIAN — Paneer & Veg curries ============
  { name: 'Palak Paneer', serving: '1 cup', calories: 300, protein: 14, carbs: 12, fat: 22 },
  { name: 'Paneer Butter Masala', serving: '1 cup', calories: 380, protein: 15, carbs: 16, fat: 28 },
  { name: 'Kadai Paneer', serving: '1 cup', calories: 340, protein: 16, carbs: 14, fat: 24 },
  { name: 'Shahi Paneer', serving: '1 cup', calories: 360, protein: 14, carbs: 16, fat: 26 },
  { name: 'Matar Paneer', serving: '1 cup', calories: 300, protein: 14, carbs: 18, fat: 18 },
  { name: 'Mixed Veg Curry', serving: '1 cup', calories: 220, protein: 6, carbs: 22, fat: 12 },
  { name: 'Aloo Gobi', serving: '1 cup', calories: 200, protein: 5, carbs: 26, fat: 9 },
  { name: 'Bhindi Masala', serving: '1 cup', calories: 180, protein: 4, carbs: 16, fat: 11 },
  { name: 'Baingan Bharta', serving: '1 cup', calories: 190, protein: 4, carbs: 16, fat: 12 },
  { name: 'Malai Kofta', serving: '1 cup', calories: 400, protein: 10, carbs: 26, fat: 28 },

  // ============ NORTH INDIAN — Non-veg ============
  { name: 'Butter Chicken', serving: '1 cup', calories: 430, protein: 30, carbs: 12, fat: 28 },
  { name: 'Chicken Tikka Masala', serving: '1 cup', calories: 380, protein: 30, carbs: 12, fat: 22 },
  { name: 'Tandoori Chicken', serving: '2 pcs', calories: 300, protein: 34, carbs: 4, fat: 16 },
  { name: 'Chicken Tikka (dry)', serving: '6 pcs', calories: 280, protein: 32, carbs: 6, fat: 14 },
  { name: 'Mutton Rogan Josh', serving: '1 cup', calories: 380, protein: 28, carbs: 8, fat: 26 },
  { name: 'Fish Tikka', serving: '6 pcs', calories: 260, protein: 30, carbs: 5, fat: 13 },
  { name: 'Egg Bhurji', serving: '2 eggs', calories: 220, protein: 14, carbs: 4, fat: 17 },

  // ============ NORTH INDIAN — Rice / Biryani ============
  { name: 'Veg Pulao', serving: '1 cup', calories: 280, protein: 6, carbs: 45, fat: 8 },
  { name: 'Jeera Rice', serving: '1 cup', calories: 250, protein: 5, carbs: 44, fat: 6 },
  { name: 'Chicken Biryani (Hyderabadi)', serving: '1 plate', calories: 540, protein: 24, carbs: 64, fat: 20 },
  { name: 'Mutton Biryani', serving: '1 plate', calories: 620, protein: 26, carbs: 64, fat: 28 },
  { name: 'Khichdi', serving: '1 cup', calories: 250, protein: 9, carbs: 42, fat: 5 },

  // ============ Indian Street Food / Chaat ============
  { name: 'Samosa', serving: '1 pc', calories: 260, protein: 4, carbs: 30, fat: 14 },
  { name: 'Pani Puri / Golgappa', serving: '6 pcs', calories: 180, protein: 4, carbs: 32, fat: 4 },
  { name: 'Bhel Puri', serving: '1 plate', calories: 250, protein: 6, carbs: 40, fat: 8 },
  { name: 'Sev Puri', serving: '6 pcs', calories: 280, protein: 6, carbs: 38, fat: 12 },
  { name: 'Pav Bhaji', serving: '1 plate', calories: 400, protein: 10, carbs: 52, fat: 17 },
  { name: 'Vada Pav', serving: '1 pc', calories: 290, protein: 7, carbs: 40, fat: 12 },
  { name: 'Aloo Tikki', serving: '2 pcs', calories: 230, protein: 5, carbs: 30, fat: 10 },
  { name: 'Dahi Puri', serving: '6 pcs', calories: 230, protein: 6, carbs: 34, fat: 8 },
  { name: 'Kachori', serving: '1 pc', calories: 250, protein: 5, carbs: 28, fat: 13 },
  { name: 'Frankie / Kathi Roll (Veg)', serving: '1 roll', calories: 320, protein: 8, carbs: 42, fat: 13 },
  { name: 'Chicken Kathi Roll', serving: '1 roll', calories: 400, protein: 20, carbs: 42, fat: 17 },

  // ============ Indian Sweets ============
  { name: 'Gulab Jamun', serving: '2 pcs', calories: 300, protein: 4, carbs: 44, fat: 12 },
  { name: 'Jalebi', serving: '50g', calories: 200, protein: 2, carbs: 36, fat: 6 },
  { name: 'Rasgulla', serving: '2 pcs', calories: 250, protein: 5, carbs: 48, fat: 4 },
  { name: 'Rasmalai', serving: '2 pcs', calories: 280, protein: 7, carbs: 36, fat: 12 },
  { name: 'Kaju Katli', serving: '3 pcs', calories: 230, protein: 5, carbs: 24, fat: 13 },
  { name: 'Laddu (Besan)', serving: '1 pc', calories: 190, protein: 3, carbs: 24, fat: 9 },
  { name: 'Barfi', serving: '1 pc', calories: 170, protein: 3, carbs: 20, fat: 9 },
  { name: 'Gajar Halwa', serving: '1 cup', calories: 340, protein: 6, carbs: 44, fat: 16 },
  { name: 'Kheer (Rice)', serving: '1 cup', calories: 280, protein: 7, carbs: 44, fat: 8 },

  // ============ BANGLADESHI ============
  { name: 'Panta Bhat', serving: '1 cup', calories: 190, protein: 4, carbs: 42, fat: 0 },
  { name: 'Bhuna Khichuri', serving: '1 cup', calories: 320, protein: 11, carbs: 48, fat: 9 },
  { name: 'Kacchi Biryani', serving: '1 plate', calories: 650, protein: 28, carbs: 68, fat: 30 },
  { name: 'Morog Polao (Chicken Pulao)', serving: '1 plate', calories: 520, protein: 24, carbs: 60, fat: 20 },
  { name: 'Tehari', serving: '1 plate', calories: 560, protein: 22, carbs: 64, fat: 24 },
  { name: 'Shorshe Ilish (Hilsa Mustard)', serving: '1 pc + gravy', calories: 320, protein: 26, carbs: 6, fat: 22 },
  { name: 'Ilish Bhaja (Fried Hilsa)', serving: '2 pcs', calories: 300, protein: 26, carbs: 3, fat: 21 },
  { name: 'Rui Macher Jhol (Rohu Curry)', serving: '1 cup', calories: 230, protein: 25, carbs: 8, fat: 11 },
  { name: 'Beef Bhuna', serving: '1 cup', calories: 380, protein: 28, carbs: 8, fat: 27 },
  { name: 'Kala Bhuna (Beef)', serving: '1 cup', calories: 420, protein: 28, carbs: 8, fat: 31 },
  { name: 'Chicken Roast (Bengali)', serving: '1 pc', calories: 340, protein: 26, carbs: 12, fat: 21 },
  { name: 'Beef Tehari', serving: '1 plate', calories: 600, protein: 24, carbs: 64, fat: 28 },
  { name: 'Aloo Bhorta', serving: '1 cup', calories: 180, protein: 4, carbs: 28, fat: 7 },
  { name: 'Begun Bhorta (Eggplant)', serving: '1 cup', calories: 160, protein: 3, carbs: 14, fat: 11 },
  { name: 'Shutki Bhuna (Dried Fish)', serving: '1 cup', calories: 260, protein: 24, carbs: 8, fat: 15 },
  { name: 'Dal (Bangladeshi)', serving: '1 cup', calories: 180, protein: 11, carbs: 26, fat: 4 },
  { name: 'Haleem', serving: '1 cup', calories: 320, protein: 20, carbs: 30, fat: 14 },
  { name: 'Fuchka', serving: '6 pcs', calories: 220, protein: 6, carbs: 36, fat: 6 },
  { name: 'Jhalmuri', serving: '1 cup', calories: 200, protein: 5, carbs: 32, fat: 7 },
  { name: 'Chotpoti', serving: '1 plate', calories: 280, protein: 10, carbs: 42, fat: 8 },
  { name: 'Mishti Doi (Sweet Yogurt)', serving: '1 cup', calories: 210, protein: 6, carbs: 36, fat: 5 },
  { name: 'Roshogolla', serving: '2 pcs', calories: 250, protein: 5, carbs: 48, fat: 4 },
  { name: 'Chomchom', serving: '1 pc', calories: 170, protein: 4, carbs: 30, fat: 4 },
  { name: 'Pitha (Bhapa)', serving: '1 pc', calories: 190, protein: 3, carbs: 36, fat: 4 },

  // ============ HOTEL / RESTAURANT — Indo-Chinese & continental ============
  { name: 'Veg Fried Rice', serving: '1 plate', calories: 380, protein: 8, carbs: 60, fat: 12 },
  { name: 'Chicken Fried Rice', serving: '1 plate', calories: 450, protein: 20, carbs: 60, fat: 15 },
  { name: 'Egg Fried Rice', serving: '1 plate', calories: 420, protein: 13, carbs: 60, fat: 14 },
  { name: 'Schezwan Fried Rice', serving: '1 plate', calories: 440, protein: 10, carbs: 62, fat: 16 },
  { name: 'Veg Noodles (Hakka)', serving: '1 plate', calories: 380, protein: 9, carbs: 56, fat: 13 },
  { name: 'Chicken Noodles', serving: '1 plate', calories: 460, protein: 20, carbs: 56, fat: 18 },
  { name: 'Gobi Manchurian', serving: '1 plate', calories: 320, protein: 7, carbs: 38, fat: 16 },
  { name: 'Chicken Manchurian', serving: '1 plate', calories: 360, protein: 24, carbs: 26, fat: 18 },
  { name: 'Chilli Chicken', serving: '1 plate', calories: 380, protein: 28, carbs: 22, fat: 20 },
  { name: 'Chilli Paneer', serving: '1 plate', calories: 360, protein: 16, carbs: 24, fat: 22 },
  { name: 'Gobi 65', serving: '1 plate', calories: 300, protein: 7, carbs: 34, fat: 15 },
  { name: 'Paneer Tikka', serving: '6 pcs', calories: 320, protein: 18, carbs: 12, fat: 22 },
  { name: 'Spring Roll (Veg)', serving: '2 pcs', calories: 260, protein: 6, carbs: 34, fat: 11 },
  { name: 'Chicken Shawarma', serving: '1 roll', calories: 480, protein: 28, carbs: 44, fat: 22 },
  { name: 'Chicken Burger', serving: '1 pc', calories: 450, protein: 24, carbs: 42, fat: 22 },
  { name: 'Veg Sandwich', serving: '1 pc', calories: 280, protein: 8, carbs: 40, fat: 9 },
  { name: 'Grilled Sandwich (Cheese)', serving: '1 pc', calories: 360, protein: 12, carbs: 40, fat: 17 },
  { name: 'French Fries', serving: '1 medium', calories: 360, protein: 4, carbs: 48, fat: 17 },
  { name: 'Cheese Pizza Slice', serving: '1 slice', calories: 285, protein: 12, carbs: 36, fat: 10 },
  { name: 'Masala Omelette (Hotel)', serving: '2 eggs', calories: 210, protein: 13, carbs: 4, fat: 16 },
  { name: 'Idli Vada Combo', serving: '2 idli + 1 vada', calories: 290, protein: 9, carbs: 40, fat: 11 },

  // ============ Common staples / proteins / fruits ============
  { name: 'Brown Rice (cooked)', serving: '1 cup', calories: 218, protein: 5, carbs: 46, fat: 2 },
  { name: 'Oats (dry)', serving: '50g', calories: 190, protein: 7, carbs: 33, fat: 3 },
  { name: 'Grilled Chicken Breast', serving: '150g', calories: 248, protein: 46, carbs: 0, fat: 5 },
  { name: 'Boiled Chickpeas', serving: '1 cup', calories: 270, protein: 15, carbs: 45, fat: 4 },
  { name: 'Paneer (raw)', serving: '100g', calories: 265, protein: 18, carbs: 4, fat: 21 },
  { name: 'Tofu', serving: '100g', calories: 145, protein: 16, carbs: 3, fat: 8 },
  { name: 'Soya Chunks (cooked)', serving: '1 cup', calories: 230, protein: 26, carbs: 18, fat: 4 },
  { name: 'Greek Yogurt', serving: '170g', calories: 100, protein: 17, carbs: 6, fat: 0 },
  { name: 'Whey Protein Scoop', serving: '30g', calories: 120, protein: 24, carbs: 3, fat: 1 },
  { name: 'Almonds', serving: '28g', calories: 164, protein: 6, carbs: 6, fat: 14 },
  { name: 'Peanuts (roasted)', serving: '30g', calories: 170, protein: 7, carbs: 5, fat: 14 },
  { name: 'Banana', serving: '1 medium', calories: 105, protein: 1, carbs: 27, fat: 0 },
  { name: 'Guava', serving: '1 medium', calories: 68, protein: 3, carbs: 14, fat: 1 },
  { name: 'Apple', serving: '1 medium', calories: 95, protein: 0, carbs: 25, fat: 0 },
  { name: 'Mango', serving: '1 cup', calories: 100, protein: 1, carbs: 25, fat: 0 },
  { name: 'Papaya', serving: '1 cup', calories: 62, protein: 1, carbs: 16, fat: 0 },
  { name: 'Orange', serving: '1 medium', calories: 62, protein: 1, carbs: 15, fat: 0 },
  { name: 'Muskmelon', serving: '1 cup', calories: 53, protein: 1, carbs: 13, fat: 0 },
  { name: 'Watermelon', serving: '1 cup', calories: 46, protein: 1, carbs: 12, fat: 0 },
]
