import { toPng } from 'html-to-image'
import { jsPDF } from 'jspdf'

export interface ReportMeal { name: string; mealType: string; calories: number; protein: number; carbs: number; fat: number }
export interface ReportData {
  who: string
  dateLabel: string
  meals: ReportMeal[]
  totals: { cal: number; p: number; c: number; f: number }
  target: number
  waterMl?: number
}

const MEAL_ICON: Record<string, string> = { breakfast: '🌅', lunch: '☀️', dinner: '🌙', snack: '🍎' }

/** Build a styled, off-screen report card to snapshot. */
function buildNode(d: ReportData): HTMLElement {
  const el = document.createElement('div')
  el.style.cssText = `position:fixed;left:-9999px;top:0;width:600px;padding:32px;box-sizing:border-box;
    font-family:Inter,system-ui,sans-serif;color:#e8eefc;
    background:linear-gradient(160deg,#0a0e1a,#06080f);border:1px solid rgba(120,160,255,.2);border-radius:20px;`
  const row = (m: ReportMeal) => `
    <div style="display:flex;justify-content:space-between;align-items:center;padding:11px 14px;margin-bottom:8px;
      background:rgba(120,160,255,.06);border:1px solid rgba(120,160,255,.12);border-radius:12px;">
      <div><div style="font-weight:700;font-size:14px">${MEAL_ICON[m.mealType] || '🍽️'} ${escapeHtml(m.name)}</div>
        <div style="font-size:11px;color:#7d89a8;text-transform:capitalize">${m.mealType} · P${m.protein} C${m.carbs} F${m.fat}</div></div>
      <div style="font-weight:800;color:#22e3ff">${m.calories}<span style="font-size:10px;color:#7d89a8"> kcal</span></div>
    </div>`
  const stat = (label: string, val: string, color: string) => `
    <div style="flex:1;text-align:center;padding:12px;background:rgba(6,8,15,.5);border:1px solid rgba(120,160,255,.12);border-radius:12px">
      <div style="font-size:22px;font-weight:800;color:${color}">${val}</div>
      <div style="font-size:10px;color:#7d89a8;text-transform:uppercase;letter-spacing:1px">${label}</div></div>`
  el.innerHTML = `
    <div style="display:flex;align-items:center;gap:12px;margin-bottom:6px">
      <div style="width:34px;height:34px;border-radius:10px;background:linear-gradient(135deg,#22e3ff,#8b5cff,#ff4fd8);
        display:grid;place-items:center;font-weight:900;color:#fff">P</div>
      <div><div style="font-weight:800;letter-spacing:3px">PULSE</div>
        <div style="font-size:10px;letter-spacing:2px;color:#7d89a8">NUTRITION REPORT</div></div>
    </div>
    <div style="font-size:13px;color:#7d89a8;margin-bottom:18px">${escapeHtml(d.who)} · ${d.dateLabel}</div>
    <div style="display:flex;gap:10px;margin-bottom:18px">
      ${stat('Calories', `${d.totals.cal}`, '#2bffb0')}
      ${stat('Protein', `${d.totals.p}g`, '#22e3ff')}
      ${stat('Carbs', `${d.totals.c}g`, '#8b5cff')}
      ${stat('Fat', `${d.totals.f}g`, '#ff4fd8')}
    </div>
    <div style="font-size:11px;color:#7d89a8;margin-bottom:14px">
      Target ${d.target} kcal · ${d.totals.cal <= d.target ? (d.target - d.totals.cal) + ' kcal under' : (d.totals.cal - d.target) + ' kcal over'}
      ${d.waterMl != null ? ` · 💧 ${(d.waterMl / 1000).toFixed(2)} L water` : ''}</div>
    ${d.meals.length ? d.meals.map(row).join('') : '<div style="color:#566184;text-align:center;padding:20px">No meals logged</div>'}
    <div style="margin-top:18px;font-size:10px;color:#566184;text-align:center">Generated by PULSE · Fitness OS</div>`
  return el
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!))
}

export async function exportNutrition(d: ReportData, fmt: 'png' | 'pdf'): Promise<void> {
  const node = buildNode(d)
  document.body.appendChild(node)
  try {
    // wait a tick so layout settles
    await new Promise((r) => setTimeout(r, 30))
    const w = node.offsetWidth
    const h = node.offsetHeight
    const dataUrl = await toPng(node, { pixelRatio: 2, backgroundColor: '#06080f', width: w, height: h })
    const fname = `pulse-nutrition-${d.dateLabel.replace(/\s+/g, '-')}`
    if (fmt === 'png') {
      const a = document.createElement('a')
      a.href = dataUrl; a.download = `${fname}.png`; a.click()
    } else {
      const pdf = new jsPDF({ orientation: h > w ? 'p' : 'l', unit: 'px', format: [w, h] })
      pdf.addImage(dataUrl, 'PNG', 0, 0, w, h)
      pdf.save(`${fname}.pdf`)
    }
  } finally {
    document.body.removeChild(node)
  }
}
